### ISSUE TITLE
Thinking error.

### ISSUE THREAD

**Issue by LvdLinde** [rlogiacco/BatterySense#11]
The "higher-on-demand.png" is wrong.
When the mosfet is 'off', and battery voltage is higher than "MCU VCC +0.5volt", current will still flow through R1 and the pin protection diode of the MCU to VCC of the MCU.

**Comment by rlogiacco** [comment]
You are totally right, I should have used a p-channel mosfet! Well spotted!

**Comment by rlogiacco** [comment]
I've fixed the README diagram, I will remove the png files
