### ISSUE TITLE
Non linear discharge model

### ISSUE THREAD

**Issue by rlogiacco** [rlogiacco/BatterySense#13]
Define a non linear discharge model better approximating the typical battery discharge curve: it doesn't have to be perfect, just accounting for rough variations.
If the model is collapsed into a function, an alternative function can be provided by the user to provide an even better and more accurate model, like via a function pointer `uint8_t (*dischargeFunction)(uint16_t)`

```cpp
void Battery::begin(uint16_t refVoltage, float dividerRatio, uint8_t (*dischargeFunction)(uint16_t)) {
  ...
}

uint8_t linearDischargeFunction(uint16_t voltage) {
  return (unsigned long)(voltage - minVoltage) * 100 / (maxVoltage - minVoltage);
}

uint8_t approxDischargeFunction(uint16_t voltage) {
  double norm = (voltage - minVoltage) / (maxVoltage - minVoltage);
  return <some math based on norm>;
}
```

**Comment by rlogiacco** [comment]
I've reached some approximation using the following two formulas: any idea which one is preferred?

- in red in the linked plot `102+(-102)/(1+(normV/(diff/1.6))^8.1)`
- in green in the linked plot `110+(-110)/(1+(normV/(diff/1.46))^6)`

In the above functions _normV_ is the normalized voltage as `voltage - minVoltage` and _diff_ is the voltage excursion, or `maxVoltage - minVoltage`.

[Plot](http://fooplot.com/#W3sidHlwZSI6MCwiZXEiOiIxMDIrKC0xMDIpLygxKyh4LygxMjAwLzEuNikpXjguMSkiLCJjb2xvciI6IiNFMzI5N0EifSx7InR5cGUiOjAsImVxIjoiMTEwKygtMTEwKS8oMSsoeC8oMTIwMC8xLjQ2KSleNikiLCJjb2xvciI6IiMxNkYyM0IifSx7InR5cGUiOjEwMDAsIndpbmRvdyI6WyIwIiwiMTIwMCIsIi0wLjUiLCIxMDAiXSwiZ3JpZCI6WyI1MCIsIjUiXSwic2hvd2F4ZXMiOjB9XQ--)

**Comment by rlogiacco** [comment]
Here another round of refinement, still not yet decided which formula best fits, but I guess one is as good as the others as it will vary on a manufacturer basis: [link to plots](https://www.desmos.com/calculator/8qzhwgphhs)

**Comment by nightmareindustries** [comment]
Great work on this library!

I have a question regarding the sigmoidal approximations: How did you choose the constant values (102, 110, 105 and the exponents)?

Thank you!

**Comment by rlogiacco** [comment]
In a very empirical way: using https://mycurvefit.com/ with a table of capacity to voltage values found on the web. 
The table was measured for a 1C discharge and we know that faster discharge rates end up in lesser capacity, but I thought it could be a good approximation.
If used in final products it would be good to replace my values with measures specific for the battery and the discharge rate of the product.

**Comment by nightmareindustries** [comment]
Thank you! This pointed me in the right direction
