### ISSUE TITLE
Double ADC read when accessing voltage and level

### ISSUE THREAD

**Issue by papylhomme** [rlogiacco/BatterySense#9]
If I read voltage and level from the sensor, the adc is used two times. This could be prevented by reusing the voltage value to compute the battery level.

    uint8t level();
    uint8t level(uint16_t voltage);

Proposed [patch](https://gist.github.com/papylhomme/e5111e4f63b63acb1ec02e107a5cd7d5)

**Comment by rlogiacco** [comment]
Seems a good addition: can you submit a pull request, please?
